### ISSUE TITLE
ps中导出xml中文乱码

### ISSUE THREAD

**Issue by zs9024** [zouhunter/FullPSD2UGUI#1]
你好，我提个小问题，ps中导出xml后，如果有中文，在unity中解析会出现乱码，可通过记事本另存为utf-8解决

**Comment by zs9024** [comment]
你好，九宫格的处理现在是跟其他图片一样，整张图片切出来的，而实际上九宫格只需要切出来一个border，请问这个可以改进吗？

**Comment by zouhunter** [comment]
谢谢你的指正，现在已经支持sliceimage了，你可以使用img这样简单的命名。
如果需要使用sliceimage可以这样:img#Custom:S，img#Common:S
这次也加入了对RawImage的支持:img#Custom:T,Img#Common:T

**Comment by zs9024** [comment]
我也处理了，并根据你的工程做了一些修改，欢迎指正。https://github.com/zs9024/quick_psd2ugui

**Comment by zouhunter** [comment]
不错不错，把ui导入变得更简单
